# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='domestic_region_dest',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='foreign_region_dest',
        ),
        migrations.AddField(
            model_name='shipment',
            name='domestic_dest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='foreign_dest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='domestic_orig',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='foreign_orig',
            field=models.IntegerField(null=True),
        ),
    ]
