INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('01','Live animals/fish');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('02','Cereal grains');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('03','Other ag prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('04','Animal feed');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('05','Meat/seafood');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('06','Milled grain prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('07','Other foodstuffs');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('08','Alcoholic beverages');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('09','Tobacco prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('10','Building stone');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('11','Natural sands');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('12','Gravel');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('13','Nonmetallic minerals');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('14','Metallic ores');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('15','Coal');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('16','Crude petroleum');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('17','Gasoline');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('18','Fuel oils');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('19','Coal-n.e.c.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('20','Basic chemicals');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('21','Pharmaceuticals');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('22','Fertilizers');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('23','Chemical prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('24','Plastics/rubber');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('25','Logs');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('26','Wood prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('27','Newsprint/paper');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('28','Paper articles');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('29','Printed prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('30','Textiles/leather');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('31','Nonmetal min. prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('32','Base metals');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('33','Articles-base metal');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('34','Machinery');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('35','Electronics');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('36','Motorized vehicles');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('37','Transport equip.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('38','Precision instruments');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('39','Furniture');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('40','Misc. mfg. prods.');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('41','Waste/scrap');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('43','Mixed freight');
INSERT INTO "Commodity" ("Commodity", "Context") VALUES ('99','Unknown');
