INSERT INTO w209."State" ("State", "Context") VALUES ('01','Alabama');
INSERT INTO w209."State" ("State", "Context") VALUES ('02','Alaska');
INSERT INTO w209."State" ("State", "Context") VALUES ('04','Arizona');
INSERT INTO w209."State" ("State", "Context") VALUES ('05','Arkansas');
INSERT INTO w209."State" ("State", "Context") VALUES ('06','California');
INSERT INTO w209."State" ("State", "Context") VALUES ('08','Colorado');
INSERT INTO w209."State" ("State", "Context") VALUES ('09','Connecticut');
INSERT INTO w209."State" ("State", "Context") VALUES ('10','Delaware');
INSERT INTO w209."State" ("State", "Context") VALUES ('11','Washington DC');
INSERT INTO w209."State" ("State", "Context") VALUES ('12','Florida');
INSERT INTO w209."State" ("State", "Context") VALUES ('13','Georgia');
INSERT INTO w209."State" ("State", "Context") VALUES ('15','Hawaii');
INSERT INTO w209."State" ("State", "Context") VALUES ('16','Idaho');
INSERT INTO w209."State" ("State", "Context") VALUES ('17','Illinois');
INSERT INTO w209."State" ("State", "Context") VALUES ('18','Indiana');
INSERT INTO w209."State" ("State", "Context") VALUES ('19','Iowa');
INSERT INTO w209."State" ("State", "Context") VALUES ('20','Kansas');
INSERT INTO w209."State" ("State", "Context") VALUES ('21','Kentucky');
INSERT INTO w209."State" ("State", "Context") VALUES ('22','Louisiana');
INSERT INTO w209."State" ("State", "Context") VALUES ('23','Maine');
INSERT INTO w209."State" ("State", "Context") VALUES ('24','Maryland');
INSERT INTO w209."State" ("State", "Context") VALUES ('25','Massachusetts');
INSERT INTO w209."State" ("State", "Context") VALUES ('26','Michigan');
INSERT INTO w209."State" ("State", "Context") VALUES ('27','Minnesota');
INSERT INTO w209."State" ("State", "Context") VALUES ('28','Mississippi');
INSERT INTO w209."State" ("State", "Context") VALUES ('29','Missouri');
INSERT INTO w209."State" ("State", "Context") VALUES ('30','Montana');
INSERT INTO w209."State" ("State", "Context") VALUES ('31','Nebraska');
INSERT INTO w209."State" ("State", "Context") VALUES ('32','Nevada');
INSERT INTO w209."State" ("State", "Context") VALUES ('33','New Hampshire');
INSERT INTO w209."State" ("State", "Context") VALUES ('34','New Jersey');
INSERT INTO w209."State" ("State", "Context") VALUES ('35','New Mexico');
INSERT INTO w209."State" ("State", "Context") VALUES ('36','New York');
INSERT INTO w209."State" ("State", "Context") VALUES ('37','North Carolina');
INSERT INTO w209."State" ("State", "Context") VALUES ('38','North Dakota');
INSERT INTO w209."State" ("State", "Context") VALUES ('39','Ohio');
INSERT INTO w209."State" ("State", "Context") VALUES ('40','Oklahoma');
INSERT INTO w209."State" ("State", "Context") VALUES ('41','Oregon');
INSERT INTO w209."State" ("State", "Context") VALUES ('42','Pennsylvania');
INSERT INTO w209."State" ("State", "Context") VALUES ('44','Rhode Island');
INSERT INTO w209."State" ("State", "Context") VALUES ('45','South Carolina');
INSERT INTO w209."State" ("State", "Context") VALUES ('46','South Dakota');
INSERT INTO w209."State" ("State", "Context") VALUES ('47','Tennessee');
INSERT INTO w209."State" ("State", "Context") VALUES ('48','Texas');
INSERT INTO w209."State" ("State", "Context") VALUES ('49','Utah');
INSERT INTO w209."State" ("State", "Context") VALUES ('50','Vermont');
INSERT INTO w209."State" ("State", "Context") VALUES ('51','Virginia');
INSERT INTO w209."State" ("State", "Context") VALUES ('53','Washington');
INSERT INTO w209."State" ("State", "Context") VALUES ('54','West Virginia');
INSERT INTO w209."State" ("State", "Context") VALUES ('55','Wisconsin');
INSERT INTO w209."State" ("State", "Context") VALUES ('56','Wyoming');
