INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('011','Birmingham AL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('012','Mobile AL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('019','Rest of AL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('020','Alaska');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('041','Phoenix AZ');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('042','Tucson AZ');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('049','Rest of AZ');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('050','Arkansas');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('061','Los Angeles CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('062','Sacramento CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('063','San Diego CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('064','San Francisco CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('065','Fresno CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('069','Rest of CA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('081','Denver CO');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('089','Rest of CO');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('091','Hartford CT');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('092','New York NY-NJ-CT-PA (CT Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('099','Rest of CT');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('101','Philadelphia PA-NJ-DE-MD (DE Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('109','Rest of DE');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('111','Washington DC-VA-MD-WV (DC Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('121','Jacksonville FL-GA  CFS Area (FL Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('122','Miami FL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('123','Orlando FL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('124','Tampa FL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('129','Rest of FL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('131','Atlanta GA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('132','Savannah GA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('139','Rest of GA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('151','Honolulu HI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('159','Rest of HI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('160','Idaho');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('171','Chicago IL-IN-WI (IL Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('172','St. Louis MO-IL (IL Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('179','Rest of IL');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('181','Chicago IL-IN-WI (IN Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('182','Indianapolis IN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('183','Fort Wayne IN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('189','Rest of IN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('190','Iowa');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('201','Kansas City MO-KS (KS Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('202','Wichita KS');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('209','Rest of KS');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('211','Cincinnati OH-KY-IN (KY Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('212','Louisville KY-IN (KY Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('219','Rest of KY');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('221','Baton Rouge LA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('222','Lake Charles LA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('223','New Orleans LA-MS (LA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('229','Rest of LA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('230','Maine');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('241','Baltimore MD');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('242','Washington DC-VA-MD-WV (MD Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('249','Rest of MD');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('251','Boston MA-RI-NH-CT (MA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('259','Rest of MA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('261','Detroit MI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('262','Grand Rapids MI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('269','Rest of MI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('271','Minneapolis-St. Paul MN-WI (MN Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('279','Rest of MN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('280','Mississippi');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('291','Kansas City MO-KS (MO Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('292','St. Louis MO-IL (MO Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('299','Rest of MO');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('300','Montana');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('311','Omaha NE-IA (NE Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('319','Rest of NE');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('321','Las Vegas NV-AZ (NV Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('329','Rest of NV');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('331','Boston MA-RI-NH-CT (NH Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('339','Rest of NH');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('341','New York NY-NJ-CT-PA (NJ Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('342','Philadelphia PA-NJ-DE-MD (NJ Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('350','New Mexico');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('361','Albany NY  CFS Area');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('362','Buffalo NY  CFS Area');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('363','New York NY-NJ-CT-PA (NY Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('364','Rochester NY');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('369','Rest of NY');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('371','Charlotte NC-SC (NC Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('372','Greensboro--Winston-Salem--High Point NC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('373','Raleigh-Durham NC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('379','Rest of NC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('380','North Dakota');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('391','Cincinnati OH-KY-IN (OH Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('392','Cleveland OH');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('393','Columbus OH');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('394','Dayton OH');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('399','Rest of OH');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('401','Oklahoma City OK');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('402','Tulsa OK');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('409','Rest of OK');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('411','Portland OR-WA (OR Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('419','Rest of OR');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('421','Philadelphia PA-NJ-DE-MD (PA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('422','Pittsburgh PA-OH-WV (PA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('423','New York NY-NJ-CT-PA (PA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('429','Rest of PA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('441','Boston MA-RI-NH-CT (RI Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('451','Charleston SC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('452','Greenville SC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('459','Rest of SC');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('460','South Dakota');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('471','Memphis TN-MS-AR (TN Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('472','Nashville TN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('473','Knoxville TN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('479','Rest of TN');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('481','Austin TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('482','Beaumont TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('483','Corpus Christi TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('484','Dallas-Fort Worth TX-OK (TX Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('485','El Paso TX-NM (TX Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('486','Houston TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('487','Laredo TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('488','San Antonio TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('489','Rest of TX');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('491','Salt Lake City UT');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('499','Rest of UT');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('500','Vermont');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('511','Richmond VA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('512','Virginia Beach-Norfolk VA-NC (VA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('513','Washington DC-VA-MD-WV (VA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('519','Rest of VA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('531','Seattle WA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('532','Portland OR-WA (WA Part)');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('539','Rest of WA');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('540','West Virginia');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('551','Milwaukee WI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('559','Rest of WI');
INSERT INTO w209."Zone" ("Zone", "Context") VALUES ('560','Wyoming');
