INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('011','Birmingham-Hoover-Talladega, AL  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('012','Mobile-Daphne-Fairhope, AL  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('019','Rest of AL');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('020','Alaska');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('042','Tucson-Nogales, AZ  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('041','Phoenix-Mesa-Glendale, AZ  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('049','Rest of AZ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('050','Arkansas');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('065','Fresno-Madera, CA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('061','Los Angeles-Long Beach, CA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('062','Sacramento-Roseville, CA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('064','San Jose-San Francisco-Oakland, CA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('063','San Diego-Carlsbad-San Marcos, CA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('069','Rest of CA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('081','Denver-Aurora, CO  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('089','Rest of CO');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('092','New York-Newark, NY-NJ-CT-PA  CFS Area (CT Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('091','Hartford-West Hartford-East Hartford, CT  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('099','Rest of CT');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('101','Philadelphia-Reading-Camden, PA-NJ-DE-MD  CFS Area (DE Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('109','Rest of DE');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('111','Washington-Arlington-Alexandria, DC-VA-MD-WV  CFS Area (DC Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('121','Jacksonville-St. Marys-Palatka, FL-GA  CFS Area (FL Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('122','Miami-Fort Lauderdale-Port St. Lucie, FL  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('123','Orlando-Deltona-Daytona Beach, FL  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('124','Tampa-St. Petersburg-Clearwater, FL  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('129','Rest of FL');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('131','Atlanta-Athens-Clarke County-Sandy Springs, GA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('132','Savannah-Hinesville-Statesboro, GA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('139','Rest of GA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('151','Urban Honolulu, HI  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('159','Rest of HI');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('160','Idaho');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('171','Chicago-Naperville, IL-IN-WI  CFS Area (IL Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('172','St. Louis-St. Charles-Farmington, MO-IL  CFS Area (IL Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('179','Rest of IL');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('181','Chicago-Naperville, IL-IN-WI  CFS Area (IN Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('183','Fort Wayne-Huntington-Auburn, IN  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('182','Indianapolis-Carmel-Muncie, IN  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('189','Rest of IN');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('190','Iowa');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('201','Kansas City-Overland Park-Kansas City, MO-KS  CFS Area (KS Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('202','Wichita-Arkansas City-Winfield, KS  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('209','Rest of KS');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('211','Cincinnati-Wilmington-Maysville, OH-KY-IN  CFS Area (KY Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('212','Louisville/Jefferson County-Elizabethtown-Madison, KY-IN  CFS Area (KY Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('219','Rest of KY');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('223','New Orleans-Metairie-Hammond, LA-MS  CFS Area (LA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('221','Baton Rouge, LA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('222','Lake Charles, LA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('229','Rest of LA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('230','Maine');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('241','Baltimore-Columbia-Towson, MD  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('242','Washington-Arlington-Alexandria, DC-VA-MD-WV  CFS Area (MD Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('249','Rest of MD');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('251','Boston-Worcester-Providence, MA-RI-NH-CT  CFS Area (MA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('259','Rest of MA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('261','Detroit-Warren-Ann Arbor, MI  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('262','Grand Rapids-Wyoming-Muskegon, MI  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('269','Rest of MI');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('271','Minneapolis-St. Paul, MN-WI  CFS Area (MN Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('279','Rest of MN');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('280','Mississippi');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('291','Kansas City-Overland Park-Kansas City, MO-KS  CFS Area (MO Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('292','St. Louis-St. Charles-Farmington, MO-IL  CFS Area (MO Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('299','Rest of MO');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('300','Montana');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('311','Omaha-Council Bluffs-Fremont, NE-IA  CFS Area (NE Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('319','Rest of NE');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('321','Las Vegas-Henderson, NV-AZ  CFS Area (NV Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('329','Rest of NV');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('331','Boston-Worcester-Providence, MA-RI-NH-CT  CFS Area (NH Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('339','Rest of NH');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('341','New York-Newark, NY-NJ-CT-PA  CFS Area (NJ Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('342','Philadelphia-Reading-Camden, PA-NJ-DE-MD  CFS Area (NJ Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('350','New Mexico');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('361','Albany-Schenectady, NY  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('362','Buffalo-Cheektowaga, NY  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('363','New York-Newark, NY-NJ-CT-PA  CFS Area (NY Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('364','Rochester-Batavia-Seneca Falls, NY  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('369','Rest of NY');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('371','Charlotte-Concord, NC-SC  CFS Area  (NC Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('372','Greensboro--Winston-Salem--High Point, NC  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('373','Raleigh-Durham-Chapel Hill, NC  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('379','Rest of NC');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('380','North Dakota');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('391','Cincinnati-Wilmington-Maysville, OH-KY-IN  CFS Area (OH Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('392','Cleveland-Akron-Canton, OH  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('393','Columbus-Marion-Zanesville, OH  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('394','Dayton-Springfield-Sidney, OH  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('399','Rest of OH');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('401','Oklahoma City-Shawnee, OK  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('402','Tulsa-Muskogee-Bartlesville, OK  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('409','Rest of OK');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('411','Portland-Vancouver-Salem, OR-WA  CFS Area (OR Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('419','Rest of OR');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('423','New York-Newark, NY-NJ-CT-PA  CFS Area (PA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('421','Philadelphia-Reading-Camden, PA-NJ-DE-MD  CFS Area (PA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('422','Pittsburgh-New Castle-Weirton, PA-OH-WV  CFS Area (PA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('429','Rest of PA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('441','Boston-Worcester-Providence, MA-RI-NH-CT  CFS Area (RI Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('452','Greenville-Spartanburg-Anderson, SC  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('451','Charleston-North Charleston-Summerville, SC  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('459','Rest of SC');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('460','South Dakota');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('473','Knoxville-Morristown-Sevierville, TN  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('471','Memphis, TN-MS-AR  CFS Area (TN Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('472','Nashville-Davidson--Murfreesboro, TN  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('479','Rest of TN');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('483','Corpus Christi-Kingsville-Alice, TX  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('484','Dallas-Fort Worth, TX-OK  CFS Area (TX Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('485','El Paso-Las Cruces, TX-NM  CFS Area (TX Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('486','Houston-The Woodlands, TX  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('481','Austin-Round Rock, TX  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('482','Beaumont-Port Arthur, TX  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('487','Laredo, TX   CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('488','San Antonio-New Braunfels, TX  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('489','Rest of TX');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('491','Salt Lake City-Provo-Orem, UT  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('499','Rest of UT');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('500','Vermont');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('512','Virginia Beach-Norfolk, VA-NC  CFS Area (VA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('511','Richmond, VA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('513','Washington-Arlington-Alexandria, DC-VA-MD-WV  CFS Area (VA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('519','Rest of VA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('532','Portland-Vancouver-Salem, OR-WA  CFS Area (WA Part)');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('531','Seattle-Tacoma, WA  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('539','Rest of WA');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('540','West Virginia');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('551','Milwaukee-Racine-Waukesha, WI  CFS Area ');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('559','Rest of WI');
INSERT INTO w209."Zone_Long" ("Zone", "Context") VALUES ('560','Wyoming');
